add a footer template to be easily overridden
bluerobotics/bluetheme pull request #14
Opened 2024-11-20 18:08 UTC by voorloopnul

2024-11-21 13:47 UTC, ES-Alexander commented on templates/attribution.html
> +Powered by <a href="" class="text-blue-br">Zola</a>
```suggestion
Powered by <a href="https://www.getzola.org/" class="text-blue-br">Zola</a>
```

2024-11-21 13:55 UTC, ES-Alexander reviewed
Hmm, I like the idea of a template so it can be fully replaced, but does it potentially _also_ make sense to include a couple of variables that can optionally be filled in the default template (e.g. the `sponsor` and `code_license` in this case)?

That way simple values can be set via the config, without needing to duplicate the existing file, but more complex ones can just replace the file entirely.

2024-11-21 13:58 UTC, voorloopnul commented
> Hmm, I like the idea of a template so it can be fully replaced, but does it potentially _also_ make sense to include a couple of variables that can optionally be filled in the default template (e.g. the `sponsor` and `code_license` in this case)?
> 
> That way simple values can be set via the config, without needing to duplicate the existing file, but more complex ones can just replace the file entirely.

Sounds fair, I'll do that.

2024-12-04 16:21 UTC, voorloopnul commented
![image](https://github.com/user-attachments/assets/45045e9e-f2f6-4bec-949a-905aaa420f7b)
![image](https://github.com/user-attachments/assets/174d3732-02a1-477d-ac78-d6e71c837852)

![image](https://github.com/user-attachments/assets/1122dc32-f8ec-40b6-a53d-07a585688208)

2024-12-04 16:41 UTC, ES-Alexander requested changes
Looking great!

Minor typo - feel free to merge after :-)

2024-12-04 16:41 UTC, ES-Alexander commented on templates/attribution.html
> +<a href="https://www.getzola.org/" class="text-blue-br">Zola</a> end
```suggestion
<a href="https://www.getzola.org/" class="text-blue-br">Zola</a> and
```

2024-12-04 17:17 UTC, merged